export const semanticTextTokens = [
  {
    name: "primary",
    cssVar: "--color-text-primary",
    value: "var(--color-gray-900)",
    primitiveRef: "Gray/900",
    why: "Primary text color for main content and headings. Ensures maximum readability.",
    whenToUse: [
      "Body text in articles and documentation",
      "Headings (h1, h2, h3)",
      "Main content areas",
      "Default text in cards and containers",
      "Navigation labels",
    ],
    avoid: "Don't use for disabled or muted text",
  },
  {
    name: "secondary",
    cssVar: "--color-text-secondary",
    value: "var(--color-gray-500)",
    primitiveRef: "Gray/500",
    why: "Secondary text for supporting information that should be less prominent.",
    whenToUse: [
      "Helper text and descriptions",
      "Metadata and timestamps",
      "Placeholder text",
      "Secondary labels",
      "Muted information",
    ],
    avoid: "Don't use for critical information that must be highly visible",
  },
  {
    name: "active",
    cssVar: "--color-text-active",
    value: "var(--color-blue-600)",
    primitiveRef: "Blue/600",
    why: "Indicates interactive or selected states. Provides clear visual feedback.",
    whenToUse: [
      "Active navigation items",
      "Selected tabs and menu items",
      "Clickable links (default state)",
      "Current step indicators",
      "Active form fields",
    ],
    avoid: "Don't use for static text that isn't interactive",
  },
  {
    name: "inverse",
    cssVar: "--color-text-inverse",
    value: "var(--color-white-900)",
    primitiveRef: "White/900",
    why: "Text color for dark backgrounds. Ensures contrast on colored or dark surfaces.",
    whenToUse: [
      "Text on dark backgrounds",
      "Text on colored buttons",
      "Text on hero sections",
      "Text on dark cards",
      "Text on gradient backgrounds",
    ],
    avoid: "Don't use on light backgrounds (will be invisible)",
  },
  {
    name: "info",
    cssVar: "--color-text-info",
    value: "var(--color-blue-800)",
    primitiveRef: "Blue/800",
    why: "Communicates informational messages and neutral status updates.",
    whenToUse: [
      "Info badges and labels",
      "Informational alerts",
      "Tooltip text",
      "Status indicators (neutral)",
      "Help text and hints",
    ],
    avoid: "Don't use for errors or warnings",
  },
  {
    name: "success",
    cssVar: "--color-text-success",
    value: "var(--color-green-800)",
    primitiveRef: "Green/800",
    why: "Indicates successful operations, confirmations, and positive states.",
    whenToUse: [
      "Success messages",
      "Completed status indicators",
      "Positive feedback text",
      "Confirmation labels",
      "Achievement badges",
    ],
    avoid: "Don't use for errors or warnings",
  },
  {
    name: "danger",
    cssVar: "--color-text-danger",
    value: "var(--color-red-800)",
    primitiveRef: "Red/800",
    why: "Highlights critical warnings and dangerous actions. Grabs immediate attention.",
    whenToUse: [
      "Destructive action labels",
      "Critical warnings",
      "Danger alerts",
      "Delete confirmation text",
      "High-priority error messages",
    ],
    avoid: "Don't use for minor errors or informational messages",
  },
  {
    name: "warning",
    cssVar: "--color-text-warning",
    value: "var(--color-yellow-800)",
    primitiveRef: "Yellow/800",
    why: "Alerts users to potential issues or actions that require attention.",
    whenToUse: [
      "Warning messages",
      "Caution labels",
      "Pending status indicators",
      "Attention-required text",
      "Precautionary notices",
    ],
    avoid: "Don't use for errors or success states",
  },
  {
    name: "accent",
    cssVar: "--color-text-accent",
    value: "var(--color-teal-800)",
    primitiveRef: "Teal/800",
    why: "Provides visual emphasis for special content and highlights.",
    whenToUse: [
      "Accent text and highlights",
      "Special feature labels",
      "Promotional text",
      "Featured content",
      "Brand-specific emphasis",
    ],
    avoid: "Don't use for standard body text",
  },
  {
    name: "error",
    cssVar: "--color-text-error",
    value: "var(--color-red-600)",
    primitiveRef: "Red/600",
    why: "Indicates errors and validation failures. Less severe than danger.",
    whenToUse: [
      "Form validation errors",
      "Error messages",
      "Failed status indicators",
      "Invalid input feedback",
      "System error notifications",
    ],
    avoid: "Don't use for destructive actions (use danger instead)",
  },
] as const;

